### ISSUE TITLE
Scope out JS editors

### ISSUE THREAD

**Issue by kcarnold** [AIToolsLab/structure#10]
The current prototype has a "text editor" mode and a "structure editor" mode (where highlighting and moving work). That's awkward; they should be able to be a single mode. So we need to find a text editor that supports the highlighting and click-to-move functionality.

Desiderata (most important first):

- Style each token (word or subword unit) with its own style, at least background color
- Scroll specific areas into view on command, get actual pixel position of things (for annotations)
- Draw links from things in main view to things in a sidebar
- Clickable things in the text that can do things (like show something in a sidebar)
- Sidebar features (possibly we implement separately)
  - comments
  - threaded comments?
  - lightweight comments
- Editing marks
  - suggestion to insert text
  - suggestion to replace some text with something else
- Simple headings (e.g., Markdown-style `## Heading 2`)

We don't need rich-text editing (bold, italic) or inserting pictures or whatever.

Possibilities:

- https://lexical.dev/
- [Quill - Your powerful rich text editor](https://quilljs.com/) - used by [[Grammarly]] (see their tech blog), handles concurrent editing; Grammarly tech blog discussed [how they augment the editor with text suggestions](https://www.grammarly.com/blog/engineering/how-suggestions-work-grammarly-editor/) even as the text changes.
- [ResourcesCo/awesome-codemirror-prosemirror: A curated list of awesome CodeMirror & ProseMirror resources](https://github.com/ResourcesCo/awesome-codemirror-prosemirror)
- Monaco: easy to add markers to specific regions of text; perhaps other annotations are pretty easy too? https://microsoft.github.io/monaco-editor/playground.html?source=v0.39.0#example-extending-language-services-model-markers-example

**Comment by kcarnold** [comment]
Another option: shift this project to be an MS Word add-in too. Then we can use the Word editor. It may not natively support all of the things we'd like.

**Comment by RayHCai** [comment]
- Lexical seems more complex
- quill is very easy to setup

**Comment by kcarnold** [comment]
It's very code-y, but maybe Monaco is worth a look? it's easy to add markers to specific regions of text; perhaps other annotations are pretty easy too? https://microsoft.github.io/monaco-editor/playground.html?source=v0.39.0#example-extending-language-services-model-markers-example

**Comment by RayHCai** [comment]
That might work, I'll have to look into it. At least for the new structure project, we need a text editor that can highlight areas of text. Do we need to have bold/italic/etc features?

**Comment by kcarnold** [comment]
Good question—no, I don't think so. I just updated the description with some actual desiderata.
